"""Initial schema

Revision ID: a471aa91dca8
Revises: 
Create Date: 2025-12-24 15:01:09.154388+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a471aa91dca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('EV', 'LV', 'DC', 'BIS', name='vehicletype'), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_vehicle_type'), 'checklist_templates', ['vehicle_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN_MONITOR', 'KARYAWAN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('no_lambung', sa.String(length=20), nullable=False),
    sa.Column('warna_no_lambung', sa.String(length=20), nullable=True),
    sa.Column('plat_nomor', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.Enum('EV', 'LV', 'DC', 'BIS', name='vehicletype'), nullable=False),
    sa.Column('merk', sa.String(length=50), nullable=True),
    sa.Column('stnk_expired', sa.Date(), nullable=True),
    sa.Column('kir_expired', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shift_type', sa.Enum('SHIFT', 'NON_SHIFT', name='shifttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_no_lambung'), 'vehicles', ['no_lambung'], unique=True)
    op.create_table('p2h_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.Enum('NORMAL', 'ABNORMAL', 'WARNING', name='inspectionstatus'), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('submission_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2h_reports_submission_date'), 'p2h_reports', ['submission_date'], unique=False)
    op.create_index(op.f('ix_p2h_reports_user_id'), 'p2h_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_p2h_reports_vehicle_id'), 'p2h_reports', ['vehicle_id'], unique=False)
    op.create_table('p2h_daily_tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_1_done', sa.Boolean(), nullable=False),
    sa.Column('shift_2_done', sa.Boolean(), nullable=False),
    sa.Column('shift_3_done', sa.Boolean(), nullable=False),
    sa.Column('shift_1_report_id', sa.UUID(), nullable=True),
    sa.Column('shift_2_report_id', sa.UUID(), nullable=True),
    sa.Column('shift_3_report_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shift_1_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['shift_2_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['shift_3_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2h_daily_tracker_date'), 'p2h_daily_tracker', ['date'], unique=False)
    op.create_index(op.f('ix_p2h_daily_tracker_vehicle_id'), 'p2h_daily_tracker', ['vehicle_id'], unique=False)
    op.create_table('p2h_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'ABNORMAL', 'WARNING', name='inspectionstatus'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['p2h_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2h_details_report_id'), 'p2h_details', ['report_id'], unique=False)
    op.create_table('telegram_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('P2H_ABNORMAL', 'P2H_WARNING', 'STNK_EXPIRY', 'KIR_EXPIRY', name='notificationtype'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_notifications_notification_type'), 'telegram_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_telegram_notifications_vehicle_id'), 'telegram_notifications', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_notifications_vehicle_id'), table_name='telegram_notifications')
    op.drop_index(op.f('ix_telegram_notifications_notification_type'), table_name='telegram_notifications')
    op.drop_table('telegram_notifications')
    op.drop_index(op.f('ix_p2h_details_report_id'), table_name='p2h_details')
    op.drop_table('p2h_details')
    op.drop_index(op.f('ix_p2h_daily_tracker_vehicle_id'), table_name='p2h_daily_tracker')
    op.drop_index(op.f('ix_p2h_daily_tracker_date'), table_name='p2h_daily_tracker')
    op.drop_table('p2h_daily_tracker')
    op.drop_index(op.f('ix_p2h_reports_vehicle_id'), table_name='p2h_reports')
    op.drop_index(op.f('ix_p2h_reports_user_id'), table_name='p2h_reports')
    op.drop_index(op.f('ix_p2h_reports_submission_date'), table_name='p2h_reports')
    op.drop_table('p2h_reports')
    op.drop_index(op.f('ix_vehicles_no_lambung'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_checklist_templates_vehicle_type'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
