"""Update schema to UUID and expiry columns

Revision ID: 5d32df75cde2
Revises: a471aa91dca8
Create Date: 2025-12-27 15:26:23.512622+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d32df75cde2'
down_revision = 'a471aa91dca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p2h_daily_tracker', sa.Column('submission_count', sa.Integer(), nullable=True))
    op.alter_column('p2h_daily_tracker', 'shift_1_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('p2h_daily_tracker', 'shift_2_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('p2h_daily_tracker', 'shift_3_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('p2h_daily_tracker', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('p2h_daily_tracker', 'created_at')
    op.add_column('p2h_details', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_index('ix_p2h_details_report_id', table_name='p2h_details')
    op.drop_column('p2h_details', 'created_at')
    op.add_column('p2h_reports', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('p2h_reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('stnk_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('kir_expiry', sa.Date(), nullable=True))
    op.drop_column('vehicles', 'stnk_expired')
    op.drop_column('vehicles', 'kir_expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('kir_expired', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('stnk_expired', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'kir_expiry')
    op.drop_column('vehicles', 'stnk_expiry')
    op.drop_column('p2h_reports', 'deleted_at')
    op.drop_column('p2h_reports', 'is_deleted')
    op.add_column('p2h_details', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_p2h_details_report_id', 'p2h_details', ['report_id'], unique=False)
    op.drop_column('p2h_details', 'is_deleted')
    op.add_column('p2h_daily_tracker', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('p2h_daily_tracker', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('p2h_daily_tracker', 'shift_3_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('p2h_daily_tracker', 'shift_2_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('p2h_daily_tracker', 'shift_1_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('p2h_daily_tracker', 'submission_count')
    # ### end Alembic commands ###
