"""reset_initial_migration

Revision ID: 033b3f0a14d4
Revises: 
Create Date: 2026-01-29 09:23:20.758628+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '033b3f0a14d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('LIGHT_VEHICLE', 'ELECTRIC_VEHICLE', 'DOUBLE_CABIN', 'SINGLE_CABIN', 'BUS', 'AMBULANCE', 'FIRE_TRUCK', 'KOMANDO', 'TRUK_SAMPAH', name='vehicletype'), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('applicable_shifts', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.String()), server_default='{"Baik", "Abnormal"}', nullable=True),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_vehicle_type'), 'checklist_templates', ['vehicle_type'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_perusahaan', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_posisi', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_active'), 'positions', ['is_active'], unique=False)
    op.create_table('work_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_statuses_is_active'), 'work_statuses', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('work_status_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'user', 'viewer', name='userrole'), nullable=False),
    sa.Column('kategori_pengguna', sa.Enum('IMM', 'TRAVEL', name='userkategori'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['work_status_id'], ['work_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('vehicle_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_types_is_active'), 'vehicle_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_types_name'), 'vehicle_types', ['name'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('no_lambung', sa.String(length=50), nullable=True),
    sa.Column('warna_no_lambung', sa.String(length=20), nullable=True),
    sa.Column('plat_nomor', sa.String(length=20), nullable=False),
    sa.Column('lokasi_kendaraan', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.Enum('Light Vehicle', 'Electric Vehicle', 'Double Cabin', 'Single Cabin', 'Bus', 'Ambulance', 'Fire Truck', 'Komando', 'Truk Sampah', name='vehicletype'), nullable=False),
    sa.Column('merk', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('no_rangka', sa.String(length=100), nullable=True),
    sa.Column('no_mesin', sa.String(length=100), nullable=True),
    sa.Column('stnk_expiry', sa.Date(), nullable=True),
    sa.Column('pajak_expiry', sa.Date(), nullable=True),
    sa.Column('kir_expiry', sa.Date(), nullable=True),
    sa.Column('kategori_unit', sa.Enum('IMM', 'TRAVEL', name='unitkategori'), nullable=False),
    sa.Column('shift_type', sa.Enum('SHIFT', 'NON_SHIFT', 'LONG_SHIFT', name='shifttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_no_lambung'), 'vehicles', ['no_lambung'], unique=True)
    op.create_index(op.f('ix_vehicles_plat_nomor'), 'vehicles', ['plat_nomor'], unique=False)
    op.create_table('p2h_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('overall_status', sa.Enum('NORMAL', 'WARNING', 'ABNORMAL', name='inspectionstatus'), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('submission_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2h_reports_submission_date'), 'p2h_reports', ['submission_date'], unique=False)
    op.create_index(op.f('ix_p2h_reports_user_id'), 'p2h_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_p2h_reports_vehicle_id'), 'p2h_reports', ['vehicle_id'], unique=False)
    op.create_table('p2h_daily_tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_1_done', sa.Boolean(), nullable=True),
    sa.Column('shift_1_report_id', sa.UUID(), nullable=True),
    sa.Column('shift_2_done', sa.Boolean(), nullable=True),
    sa.Column('shift_2_report_id', sa.UUID(), nullable=True),
    sa.Column('shift_3_done', sa.Boolean(), nullable=True),
    sa.Column('shift_3_report_id', sa.UUID(), nullable=True),
    sa.Column('final_status', sa.Enum('GREEN', 'YELLOW', 'RED', name='finalstatus'), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_1_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['shift_2_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['shift_3_report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2h_daily_tracker_date'), 'p2h_daily_tracker', ['date'], unique=False)
    op.create_index(op.f('ix_p2h_daily_tracker_vehicle_id'), 'p2h_daily_tracker', ['vehicle_id'], unique=False)
    op.create_table('p2h_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'WARNING', 'ABNORMAL', name='inspectionstatus'), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['p2h_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('P2H_ABNORMAL', 'P2H_WARNING', 'STNK_EXPIRY', 'KIR_EXPIRY', name='notificationtype'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['p2h_reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_notifications_notification_type'), 'telegram_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_telegram_notifications_vehicle_id'), 'telegram_notifications', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_notifications_vehicle_id'), table_name='telegram_notifications')
    op.drop_index(op.f('ix_telegram_notifications_notification_type'), table_name='telegram_notifications')
    op.drop_table('telegram_notifications')
    op.drop_table('p2h_details')
    op.drop_index(op.f('ix_p2h_daily_tracker_vehicle_id'), table_name='p2h_daily_tracker')
    op.drop_index(op.f('ix_p2h_daily_tracker_date'), table_name='p2h_daily_tracker')
    op.drop_table('p2h_daily_tracker')
    op.drop_index(op.f('ix_p2h_reports_vehicle_id'), table_name='p2h_reports')
    op.drop_index(op.f('ix_p2h_reports_user_id'), table_name='p2h_reports')
    op.drop_index(op.f('ix_p2h_reports_submission_date'), table_name='p2h_reports')
    op.drop_table('p2h_reports')
    op.drop_index(op.f('ix_vehicles_plat_nomor'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_no_lambung'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_types_name'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_is_active'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_work_statuses_is_active'), table_name='work_statuses')
    op.drop_table('work_statuses')
    op.drop_index(op.f('ix_positions_is_active'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_checklist_templates_vehicle_type'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
