"""update_roles_to_simple_3_levels

Revision ID: 766f15b23a80
Revises: f97c42078b74
Create Date: 2026-01-05 11:29:15.260811+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766f15b23a80'
down_revision = 'f97c42078b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
