"""add_tags_and_shifts_to_checklist

Revision ID: 615b363ece3a
Revises: 68aa157fa22f
Create Date: 2026-01-06 11:01:29.823554+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615b363ece3a'
down_revision = '68aa157fa22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
