"""create_master_data_and_p2h_tables

Revision ID: f97c42078b74
Revises: 5d32df75cde2
Create Date: 2026-01-05 10:43:06.602215+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f97c42078b74'
down_revision = '5d32df75cde2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- PERBAIKAN MANUAL: Buat tipe ENUM di PostgreSQL ---
    final_status_enum = postgresql.ENUM('GREEN', 'YELLOW', 'RED', name='finalstatus')
    final_status_enum.create(op.get_bind())
    
    user_kategori_enum = postgresql.ENUM('IMM', 'TRAVEL', name='userkategori')
    user_kategori_enum.create(op.get_bind())
    
    unit_kategori_enum = postgresql.ENUM('IMM', 'TRAVEL', name='unitkategori')
    unit_kategori_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_perusahaan', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_department', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_posisi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Gunakan tipe enum yang sudah dibuat di atas
    op.add_column('p2h_daily_tracker', sa.Column('final_status', sa.Enum('GREEN', 'YELLOW', 'RED', name='finalstatus'), nullable=True))
    op.add_column('p2h_details', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_constraint('p2h_details_report_id_fkey', 'p2h_details', type_='foreignkey')
    op.create_foreign_key(None, 'p2h_details', 'p2h_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.add_column('p2h_reports', sa.Column('odometer', sa.Integer(), nullable=True))
    op.add_column('p2h_reports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('no_handphone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('position_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('work_status_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('kategori_pengguna', sa.Enum('IMM', 'TRAVEL', name='userkategori'), nullable=False))
    
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'users', 'work_statuses', ['work_status_id'], ['id'])
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    
    op.add_column('vehicles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('no_rangka', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('no_mesin', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('pajak_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('kategori_unit', sa.Enum('IMM', 'TRAVEL', name='unitkategori'), nullable=False))
    
    op.alter_column('vehicles', 'no_lambung',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('vehicles', 'plat_nomor',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicles', 'merk',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_vehicles_plat_nomor'), 'vehicles', ['plat_nomor'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_plat_nomor'), table_name='vehicles')
    op.alter_column('vehicles', 'merk',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('vehicles', 'plat_nomor',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('vehicles', 'no_lambung',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('vehicles', 'kategori_unit')
    op.drop_column('vehicles', 'pajak_expiry')
    op.drop_column('vehicles', 'no_mesin')
    op.drop_column('vehicles', 'no_rangka')
    op.drop_column('vehicles', 'user_id')
    op.drop_column('vehicles', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'kategori_pengguna')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'work_status_id')
    op.drop_column('users', 'position_id')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'no_handphone')
    op.drop_column('p2h_reports', 'updated_at')
    op.drop_column('p2h_reports', 'odometer')
    op.drop_constraint(None, 'p2h_details', type_='foreignkey')
    op.create_foreign_key('p2h_details_report_id_fkey', 'p2h_details', 'p2h_reports', ['report_id'], ['id'])
    op.drop_column('p2h_details', 'image_url')
    op.drop_column('p2h_daily_tracker', 'final_status')
    op.drop_table('work_statuses')
    op.drop_table('positions')
    op.drop_table('departments')
    op.drop_table('companies')
    
    # --- PERBAIKAN MANUAL: Hapus tipe ENUM saat downgrade ---
    sa.Enum(name='finalstatus').drop(op.get_bind())
    sa.Enum(name='userkategori').drop(op.get_bind())
    sa.Enum(name='unitkategori').drop(op.get_bind())
    # ### end Alembic commands ###