"""Create telegram_users table for tracking user subscriptions to bot

Revision ID: telegram_users_001
Revises: a553b45fe239
Create Date: 2026-02-05 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'telegram_users_001'
down_revision = 'a553b45fe239'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'telegram_users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('chat_id', sa.String(50), nullable=False),
        sa.Column('first_name', sa.String(255), nullable=True),
        sa.Column('last_name', sa.String(255), nullable=True),
        sa.Column('username', sa.String(255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('last_notification_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chat_id'),
        extend_existing=True
    )
    op.create_index(op.f('ix_telegram_users_chat_id'), 'telegram_users', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_username'), 'telegram_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_users_username'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_chat_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
