"""add_tags_and_shifts_to_checklist

Revision ID: 68aa157fa22f
Revises: 766f15b23a80
Create Date: 2026-01-06 09:39:32.475404+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68aa157fa22f'
down_revision = '766f15b23a80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_templates', sa.Column('vehicle_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('checklist_templates', sa.Column('applicable_shifts', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('checklist_templates', sa.Column('options', postgresql.ARRAY(sa.String()), server_default='{"Baik", "Abnormal"}', nullable=True))
    op.alter_column('checklist_templates', 'vehicle_type',
               existing_type=postgresql.ENUM('EV', 'LV', 'DC', 'BIS', name='vehicletype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_templates', 'vehicle_type',
               existing_type=postgresql.ENUM('EV', 'LV', 'DC', 'BIS', name='vehicletype'),
               nullable=False)
    op.drop_column('checklist_templates', 'options')
    op.drop_column('checklist_templates', 'applicable_shifts')
    op.drop_column('checklist_templates', 'vehicle_tags')
    # ### end Alembic commands ###
